meta_data:
  script_path: run_scripts/sac_exp_script.py
  exp_name: hopper_online_sac_train_policy_for_l2s_genq
  description: Online sac,Hopper
  num_workers: 12 # 64
  num_gpu_per_worker: 1 # 1 
  num_cpu_per_worker: 4 # 2
  mem_per_worker: 10gb
  partitions: cpu
  node_exclusions: gpu048,gpu024,gpu025,gpu012,gpu027
# -----------------------------------------------------------------------------
variables:
  seed: [9999]

  sac_params:
    policy_lr: [0.0003] #[0.001,0.0001,0.0005,0.00005] [0.0003]
    qf_lr: [0.0003] #[0.001]
    reward_scale: [30.0] # 5.0,30.0


# -----------------------------------------------------------------------------
constants:
  test: false # true

  policy_net_size: 256
  policy_num_hidden_layers: 2    

  sac_params:
    #reward_scale: 5.0
    discount: 0.99
    soft_target_tau: 0.005
    beta_1: 0.25
  
  alg_params:
    batch_size: 256
    if_save_policy: true
    policy_save_freq: 50

    num_epochs: 16200
    num_steps_per_epoch: 1000
    num_steps_between_train_calls: 100
    num_update_loops_per_train_call: 100
    max_path_length: 1000
    min_steps_before_training: 1000

    eval_deterministic: true
    num_steps_per_eval: 1000
    
    replay_buffer_size: 1000000
    no_terminal: false
    wrap_absorbing: false

    save_best: true
    freq_saving: 10
    save_replay_buffer: false
    save_environment: false
    save_algorithm: false
  
  env_specs:
    env_name: 'hopper'
    env_kwargs: {}
    eval_env_seed: 78236
    training_env_seed: 24495
